package edu.eci.cosw.samples.model;
// Generated 9/10/2015 03:08:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Mensajeros generated by hbm2java
 */
@Entity
@Table(name="EmpleadosEPS"
)
public class EmpleadoEPS  implements java.io.Serializable {


     private int idEmpleadoEPS;
     private String nombre; 
     private Integer telefono;
     private Epsafilida epsPertenece;
    
   

    public EmpleadoEPS() {
    }

    public EmpleadoEPS(int idEmpleadoEPS) {
        this.idEmpleadoEPS = idEmpleadoEPS;
    }

    public EmpleadoEPS(int idEmpleadoEPS, String nombre, Integer telefono, Epsafilida epsPertenece) {
        this.idEmpleadoEPS = idEmpleadoEPS;
        this.nombre = nombre;
        this.telefono = telefono;
        this.epsPertenece = epsPertenece;
    }

    
    @Id 
    @Column(name="idEmpleadoEPS", unique=true, nullable=false)
    public int getIdEmpleadoEPS() {
        return idEmpleadoEPS;
    }

    public void setIdEmpleadoEPS(int idEmpleadoEPS) {
        this.idEmpleadoEPS = idEmpleadoEPS;
    }
    
     
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    
    
    @Column(name="telefono")
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="epsPertenece")
    public Epsafilida getEpsPertenece() {
        return epsPertenece;
    }

    public void setEpsPertenece(Epsafilida epsPertenece) {
        this.epsPertenece = epsPertenece;
    }


}


